name: cd

on:
  push:
    branches: [main]

jobs:
  tests:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: check out code
        uses: actions/checkout@v3

      - name: build production artifact
        run: ./scripts/buildprod.sh
