name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run tests within code
        run: go test ./... -cover

      - name: Check for any security issues using gosec
        run: gosec ./...
