name: style

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: formatting
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Check out code
        uses: actions/checkout@v3

      - name: Format all of the code
        run: test -z $(go fmt ./...)

      - name: check for any issues with staticcheck
        run: staticcheck ./...
